### ISSUE TITLE
lang-region with globalize-webpack-plugin

### ISSUE THREAD

**Issue by MattWButler** [rxaviers/globalize-webpack-plugin#24]
Related to this issue: https://github.com/jquery/globalize/issues/357

Does the globalize-webpack-plugin provide lang-region support?

For example, I want my application to use this loader with webpack and have support for en-US and en-GB.

**Comment by rxaviers** [comment]
Hi, yes it does. Currently, it does for all the available bundles (example [here](https://github.com/unicode-cldr/cldr-numbers-full/tree/master/main) for newest CLDR 29). It should support any locale (i.e., any combination of language-region-script) like Globalize does, but this plugin currently doesn't know how to figure out how to map a locale to a bundle (this is easily fixable by using cldrjs).

**Comment by rxaviers** [comment]
I've updated by above comment.

**Comment by MattWButler** [comment]
Thanks @rxaviers for your response! I appreciate all your work on this project too!

**Comment by rxaviers** [comment]
You're welcome, thanks. If you need the part of using arbitrary locales and want to contribute that, I could help guide where to look at, just let me know.
