### ISSUE TITLE
updates for webpack 2?

### ISSUE THREAD

**Issue by stokes571** [rxaviers/globalize-webpack-plugin#29]
Just wondering if there is a plan to update this plugin for webpack 2.  Thanks.

**Comment by rxaviers** [comment]
Hi, there's no work in progress, but I'd be definitely open to accept a PR. Thanks

**Comment by necolas** [comment]
Just discovered that `skip-amd-webpack-plugin` (used by this plugin) doesn't work with webpack@2 as it's using APIs that don't exist anymore.

**Comment by rxaviers** [comment]
Thanks for bringing it up. The good news is that this plugin is very small.
If it's only about the compiler plugin API, it's hopefully a quick change.

>

-- 
+55 (16) 98138-1583, skype: rxaviers
http://rafael.xavier.blog.br

**Comment by R74NN** [comment]
Hi, is there currently a workaround to make the plugin work with webpack 2?
