### ISSUE TITLE
Use subtags to extract language from locale.

### ISSUE THREAD

**Issue by lijunle** [rxaviers/globalize-webpack-plugin#31]
Hi, @rxaviers 

The current [implementation](https://github.com/rxaviers/globalize-webpack-plugin/blob/master/util.js#L19) use `locale` directly to construct the path.

However, only the [language](https://github.com/rxaviers/cldrjs/blob/master/src/core/subtags.js#L44) from the `subtags(locale)` should be passed.

**Comment by rxaviers** [comment]
Hi, sorry for the delay.

Isn't that `locale` simply a variable that maps whatever String was passed in the config file as `developmentLocale`?

Please, can you explain your line of thought?

Thanks
