### ISSUE TITLE
Commit c0a1971 breaks support for Webpack 1.14.0.

### ISSUE THREAD

**Issue by tristanfisher** [rxaviers/globalize-webpack-plugin#35]
The change from:

`var ConcatSource = require("webpack/lib/ConcatSource");` to `var ConcatSource = require("webpack-sources").ConcatSource;` in ProductionModePlugin.js breaks globalize-webpack-plugin building in Webpack 1.14.0.  

https://github.com/rxaviers/globalize-webpack-plugin/commit/c0a1971e792267bbd5ed35a441fc117ac0e266dd

There is also an expectation later that ConcatSource will have a constructor (e.g. `compilation.assets[file] = new ConcatSource(source);`).

I left a comment on the commit before realizing this is probably best as a GH issue.

**Comment by rxaviers** [comment]
@tristanfisher could you please provide a reduced test case?

**Comment by tristanfisher** [comment]
@rxaviers : apologies for the delay; I ended up having less time for work during the holidays than expected.  I made a trivial test case and could _not_ reproduce in that fresh project, even though upgrading in an existing project ran into this error.  

I'm wholly willing to accept this is just some weirdness with my local, so please feel free to close this issue.  If I figure out which combination of factors caused my errors, I'll let you know (with code attached).

Sorry for stealing your focus and happy new year.

**Comment by rxaviers** [comment]
Thank you, when we have a reproducible steps, we can reopen.
