### ISSUE TITLE
Doesn't build on windows

### ISSUE THREAD

**Issue by rxaviers** [rxaviers/globalize-webpack-plugin#7]
Original: https://github.com/jquery/globalize/issues/516

> Unless I am missing something, I don't think globalize-webpack-plugin would build on windows... I am thinking regular expressions might be the problem:

    
>
    GlobalizeCompilerHelper.prototype.getModuleFilepath = function(request) {
      return path.join(this.tmpdir, request.replace(/.*!/, "").replace(/[/?" ]/g, "-"));
    };

>**ERROR in ./app/index.js**
Module parse failed: C:\app-npm-webpack\app\index.js ENOENT, no such file or directory 'C:\app-npm-webpack\.tmp-globalize-webpack\C:\app-npm-webpack\app\index.js'
You may need an appropriate loader to handle this file type.
Error: ENOENT, no such file or directory 'C:\app-npm-webpack\.tmp-globalize-webpack\C:\app-npm-webpack\app\index.js'

Jörn has added this comment:
> Classic Windows path issue. Should be easy enough to fix. While at it, set up CI on Windows? http://www.appveyor.com/ makes that reasonably easy.

**Comment by rxaviers** [comment]
> Hi Rafael,

> Yes, I would like to try to make it work on Windows as this is our dev
environment. I'd appreciate if you could give me some guidance.
I tried a quick&dirty fix,

> GlobalizeCompilerHelper.prototype.getModuleFilepath = function(request) {
  return path.join(this.tmpdir, request.replace(/.*!/,
"").replace(/[/?" \\:]/g, "-"));
};

> but it goes one step farther and fails at

@anaritsin, your change seems correct to me. One more regexp will need update as well:

- https://github.com/rxaviers/globalize-webpack-plugin/blob/6e5fd07f58f6fe080ca0e5939fb9a92a211ab4ed/DevelopmentModePlugin.js#L37:

```diff
- compiler.apply(new SkipAMDPlugin(/(^|\/)globalize($|\/)/));
+ compiler.apply(new SkipAMDPlugin(/(^|[/\\])globalize($|[/\\])/));
```

**Comment by warstick** [comment]
@rxaviers 
As you suggested i followed following steps.
1) Changed the getModuleFilepath in globalizecompilerhelper.js.

GlobalizeCompilerHelper.prototype.getModuleFilepath = function(request) {
return path.join(this.tmpdir, request.replace(/.*!/,
"").replace(/[/?" \:]/g, "-"));
};

2) Change complier.apply in DevlopmentModePlugin.js.

compiler.apply(new SkipAMDPlugin(/(^|\/)globalize($|\/)/));

My Output:
![error](https://cloud.githubusercontent.com/assets/1407190/10253801/0ccd37e6-695d-11e5-8aee-53c9685013ae.PNG)

**Comment by rxaviers** [comment]
1)

> GlobalizeCompilerHelper.prototype.getModuleFilepath = function(request) {
return path.join(this.tmpdir, request.replace(/.*!/,
"").replace(/[/?" :]/g, "-"));
};

It's missing the `\` char as well. So:

```js
GlobalizeCompilerHelper.prototype.getModuleFilepath = function(request) {
return path.join(this.tmpdir, request.replace(/.*!/,
"").replace(/[/?" :\\]/g, "-"));
};
```

2) You haven't changed anything there? Use

```js
compiler.apply(new SkipAMDPlugin(/(^|[/\\])globalize($|[/\\])/));
```

**Comment by anaritsin** [comment]
I tried the 

     compiler.apply(new SkipAMDPlugin(/(^|[/\\])globalize($|[/\\])/));

but it did not work for me.

Also if I want to build it in 'production' mode, should not it be changed in the ProductionModePlugin ?

**Comment by warstick** [comment]
@rxaviers 

Thanks it worked. but i got some other error.

![error-1](https://cloud.githubusercontent.com/assets/1407190/10255116/caf60880-6965-11e5-90b1-64efa51ce6b2.PNG)

**Comment by rxaviers** [comment]
> Also if I want to build it in 'production' mode, should not it be changed in the ProductionModePlugin ? 

@anaritsin Yeap.

**Comment by rxaviers** [comment]
@warstick, it seems `SkipAMDPlugin` didn't work. It could be related to what @anaritsin said above.

It seems like you both are working on the same fix. If you create a PR you both could work together in the solution. I'm happy to assist as time permits.

**Comment by anaritsin** [comment]
@warstick @rxaviers 
this is exactly where i got stuck - SkipAMDPlugin did not work. And this is what I tried:

    compiler.apply(
    // Skip AMD part of Globalize Runtime UMD wrapper.
    //globalizeSkipAMDPlugin = new SkipAMDPlugin(/(^|\/)globalize($|\/)/),
      globalizeSkipAMDPlugin = new SkipAMDPlugin(/(^|[/\\])globalize($|[/\\])/),

    // Replaces `require("globalize")` with `require("globalize/dist/globalize-runtime")`.
    //new NormalModuleReplacementPlugin(/(^|\/)globalize$/, "globalize/dist/globalize-runtime"),
      new NormalModuleReplacementPlugin(/(^|[/\\])globalize$/, "globalize/dist/globalize-runtime"),

    // Skip AMD part of Globalize Runtime UMD wrapper.
      //new SkipAMDPlugin(/(^|\/)globalize-runtime($|\/)/)
    new SkipAMDPlugin(/(^|[/\\])globalize-runtime($|[/\\])/)
  );

**Comment by rxaviers** [comment]
On your local `node_modules/skip-amd-webpack-plugin/index.js`, inspect `this.state.current.request` by adding a `console.log(this.state.current.request)` at https://github.com/rxaviers/skip-amd-webpack-plugin/blob/master/index.js#L23 and https://github.com/rxaviers/skip-amd-webpack-plugin/blob/master/index.js#L30. Let's see how this is in Windows. It's also good to inspect the result of `self.requestRegExp.test(this.state.current.request)`.

**Comment by anaritsin** [comment]
@rxaviers 
the L23 is this:
1 this.state.current.request==>> C:\app-npm-webpack\node_modules\globalize\dist\globalize-runtime.js
1 this.state.current.request==>> C:\app-npm-webpack\node_modules\globalize\dist\globalize-runtime\number.js
1 this.state.current.request==>> C:\app-npm-webpack\node_modules\globalize\dist\globalize-runtime\message.js
1 this.state.current.request==>> C:\app-npm-webpack\node_modules\globalize\dist\globalize-runtime\currency.js
1 this.state.current.request==>> C:\app-npm-webpack\node_modules\globalize\dist\globalize-runtime\date.js
1 this.state.current.request==>> C:\app-npm-webpack\node_modules\globalize\dist\globalize-runtime\relative-time.js
1 this.state.current.request==>> C:\app-npm-webpack\node_modules\globalize\dist\globalize-runtime\plural.js


the L30 - never executes

**Comment by rxaviers** [comment]
The regexp should work.

```js
/(^|[/\\])globalize-runtime($|[/\\])/.test("C:\\app-npm-webpack\\node_modules\\globalize\\dist\\globalize-runtime\\message.js")
// > true
```

Could you inspect the result of `self.requestRegExp.test(this.state.current.request)` as well?

**Comment by anaritsin** [comment]
1 this.state.current.request==>> C:\app-npm-webpack\node_modules\globalize\dist\globalize-runtime.js
	1 self.requestRegExp.test(this.state.current.request)==>> true
	1 this.state.current.request==>> C:\app-npm-webpack\node_modules\globalize\dist\globalize-runtime\number.js
	1 self.requestRegExp.test(this.state.current.request)==>> true
	1 this.state.current.request==>> C:\app-npm-webpack\node_modules\globalize\dist\globalize-runtime\plural.js
	1 self.requestRegExp.test(this.state.current.request)==>> true
	1 this.state.current.request==>> C:\app-npm-webpack\node_modules\globalize\dist\globalize-runtime\message.js
	1 self.requestRegExp.test(this.state.current.request)==>> true
	1 this.state.current.request==>> C:\app-npm-webpack\node_modules\globalize\dist\globalize-runtime\date.js
	1 self.requestRegExp.test(this.state.current.request)==>> true
	1 this.state.current.request==>> C:\app-npm-webpack\node_modules\globalize\dist\globalize-runtime\relative-time.js
	1 self.requestRegExp.test(this.state.current.request)==>> true
	1 this.state.current.request==>> C:\app-npm-webpack\node_modules\globalize\dist\globalize-runtime\currency.js
	1 self.requestRegExp.test(this.state.current.request)==>> true
	1 this.state.current.request==>> C:\app-npm-webpack\.tmp-globalize-webpack\C--app-npm-webpack-app-index.js
	1 self.requestRegExp.test(this.state.current.request)==>> false
	1 this.state.current.request==>> C:\app-npm-webpack\.tmp-globalize-webpack\C--app-npm-webpack-app-index.js
	1 self.requestRegExp.test(this.state.current.request)==>> false
	Hash: 3cc7abe35aac638043d9
	Version: webpack 1.12.2
	Time: 2138ms

**Comment by box-turtle** [comment]
Anybody get this working?

**Comment by warstick** [comment]
Nope.

On Mon, Oct 19, 2015 at 6:10 PM, box-turtle <notifications@github.com>
wrote:

> Anybody get this working?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rxaviers/globalize-webpack-plugin/issues/7#issuecomment-149202319>
> .
>



-- 
*Thanks & Regards,*

*Manikanta Srirangam.*

*Contact No: +91-9866348399*

**Comment by rxaviers** [comment]
I'd be happy to merge a fix or to assist finding one.

**Comment by aruberto** [comment]
I was able to get past the globalize-runtime/<module> not found issues by disabling AMD on the tmp files themselves. I added

new SkipAMDPlugin(new RegExp(this.tmpdir.replace(/(?=[\/\\^$*+?.()|{}[\]])/g, "\\")))

to ProductionModePlugin, and webpack completes successfully. However still think something is wrong since get following errors when opening the page that's built:

![image](https://cloud.githubusercontent.com/assets/9933826/12404857/5735a002-be0d-11e5-9fd2-ee45f3bf0b7e.png)

**Comment by rxaviers** [comment]
@aruberto does development mode work for you? Can you give more information about the 'call' of undefined error (e.g., what's in vendor.js line 51)?

**Comment by aruberto** [comment]
Hey @rxaviers 

I've put what I've done so far in https://github.com/aruberto/globalize-webpack-plugin/tree/windows-fix

Here are the dist files that get generated from the app-npm-webpack project using my modified globalize-webpack-plugin on Windows and UglifyJS disabled:

[dist.zip](https://github.com/rxaviers/globalize-webpack-plugin/files/96050/dist.zip)

I get following errors when opening index.html in chrome

![image](https://cloud.githubusercontent.com/assets/9933826/12422118/4e5d8a86-be93-11e5-85c2-40cdcd2c3ef6.png)


As for development mode, it never gave webpack errors even before my changes, however visting localhost:8080/index.html gives following error:


![image](https://cloud.githubusercontent.com/assets/9933826/12422049/fee0b654-be92-11e5-988f-f03623fc5489.png)

It is pretty much what https://github.com/jquery/globalize/issues/551 is complaining about

**Comment by aruberto** [comment]
Doing a diff between files generated on Linux and Windows (), I notice this is off with i18n files.

On Linux, the i18n files end with something like:

```
module.exports = __webpack_require__(2);
```

however on Windows they end with

```
module.exports = __webpack_require__(undefined);
```

**Comment by aruberto** [comment]
The issue with endings of the i18n files is the splits in utils.js

changing

```
filepath.split( "/" )
```

to

```
filepath.split( /[\/\\]/ )
```

fixes ends of i18n files. 

However still stuck on issue with module.exports = factory line ...

**Comment by aruberto** [comment]
I've got the dev plugin working as well. 

I've submitted #12 which should fix this issue and https://github.com/jquery/globalize/issues/551

**Comment by rxaviers** [comment]
Awesome, just confirming is it all working on Windows now using your fix?

**Comment by aruberto** [comment]
Yes dev and prod modes both work for me with https://github.com/jquery/globalize/tree/master/examples/app-npm-webpack project
