### ISSUE TITLE
Peer dependency warning due to old version of dependency.

### ISSUE THREAD

**Issue by ScriptWorker** [rxaviers/globalize-webpack-plugin#72]
I've installed globalize-webpack-plugin and I can see in console the message:
npm WARN skip-amd-webpack-plugin@0.1.3 requires a peer of webpack@^1.9.0 || ^2.2.0 but none was installed.

I have installed:
webpack@3.4.1

This message is because of old version of skip-amd-webpack-plugin listed in dependencies (skip-amd-webpack-plugin 0.1.x, but it should be 0.2.x)

Should I make PR with updated version?

**Comment by rxaviers** [comment]
Thanks for reporting this issue, it required a dependency bump. Did it now, released on:

+ globalize-webpack-plugin@2.0.1

**Comment by ScriptWorker** [comment]
Thank you for so fast response and fix!
