### ISSUE TITLE
"TypeError: e[r] is undefined" dumped by production build, webpack 3

### ISSUE THREAD

**Issue by emacsuser123** [rxaviers/globalize-webpack-plugin#78]
Hello.

When I run the _app-npm-webpack_ example app using the package versions currently defined on github master branch, everything goes OK, both for development and production runs.

But when I upgrade webpack version to 3.10 (latest stable), also upgrading globalize* packages to their latest stable versions, the production run fails with 

> TypeError: e[r] is undefined

 error.

I have the same problem with my own applications that make use of globalize library.

Thanks.
-Bob V

**Comment by rxaviers** [comment]
Fix coming #88
