### ISSUE TITLE
example not working with 

### ISSUE THREAD

**Issue by imsontosh** [rxaviers/globalize-webpack-plugin#80]
Hello, 

Thanks for the Nice product i.e. globalize. I have some issue while integrating with webpack and react application. i followed the webpack integration example 

https://github.com/globalizejs/globalize/tree/master/examples/app-npm-webpack

However the example is not working with webpack 2.7.0.

In dev mode application working for first time. on second time onwards, it's not working. webpack build is failing

In prod mode example is not at all working.

It would be a great help if you can set an example for webpack 2.7.0.

Thanks for your support.

**Comment by ambrons** [comment]
You should look at some of the work here with webpack 3.  Still some issues that are being worked on
https://github.com/globalizejs/globalize/pull/812

**Comment by rxaviers** [comment]
Fix coming... Please see #88
