### ISSUE TITLE
Using Globalize Webpack Plugin with dynamic localization data imports

### ISSUE THREAD

**Issue by aapoalas** [rxaviers/globalize-webpack-plugin#82]
Hello

I'm trying my absolute hardest to use your lovely plugin, but cannot fathom how I to use it with dynamic language settings and dynamic messages / formatters.

I have gathered that I need to not use the Runtime Globalize but is there any way to still use Globalize Webpack Plugin to precompile a set of supported locale chunks / bundles, and then import those dynamically in code?

I can't really find an example that would open up the issue to me. To elaborate: We have our own l10n service running in the app that wraps Globalize. Inside we have dynamic requires / imports (currently using RequireJS) to get all the CLDR data etc for reasons, as well as dynamic imports for messages that come from a remote. The latter part is where our need to use Globalize instead of Globalize-Runtime comes from. Now I'd love it if I could have Webpack prepackage and serve the CLDR data we need for each of our supported locale.

Is there any way to make this happen with this Plugin?

**Comment by sylvanaar** [comment]
Just as a bystander I am trying to visualize what you are asking for. It sounds like you are doing things at runtime, what is it you want to precompile? The CLDR data, this project is about using the CLDR data to precompile the formatters so you do not have to serve the CLDR data to the client. What you are asking for seems like it may be something entirely different than the purpose of this project.

**Comment by rxaviers** [comment]
I'm closing this bug as I understand the question has been answered.

**Comment by metaclass-nl** [comment]
Maybe https://github.com/metaclass-nl/switch-language-example-globalize could be interesting for this
