### ISSUE TITLE
Webpack 4 support

### ISSUE THREAD

**Issue by wshamim** [rxaviers/globalize-webpack-plugin#83]
Hi, I am thinking to upgrade to Webpack 4. 

Just want to ask if it is in your plans to add its support?

Cheers

**Comment by rxaviers** [comment]
I'd be open to include any necessary upgrades

**Comment by marvinhagemeister** [comment]
Together with @jzaefferer we made a stab at trying to port it to `webpack4`. There are a few api changes here and there for plugins, but we couldn't get the cldr data to be bundled correctly. We gave up after an hour or so of trying, but this seems to be doable for someone with more initimate knowledge of the internals of `globalizejs`

**Comment by mgvparas** [comment]
any updates on this?

**Comment by rxaviers** [comment]
Webpack 4 had a breaking change for plugins/loaders https://github.com/webpack/webpack/releases/tag/v4.0.0

**Comment by rxaviers** [comment]
Yeap, it requires significant rewrite (and major bump)...

I have updated a dependency to support webpack 4 https://github.com/rxaviers/skip-amd-webpack-plugin/pull/7

**Comment by jzaefferer** [comment]
Sounds like the updated skip-amd-webpack-plugin is only a small part of that?

As for the v4 plugin API, this seems to be up-to-date and more helpful than the changelog: https://webpack.js.org/api/plugins/

And there's a migration guide here, for 'plugin and loader authors': https://medium.com/webpack/webpack-4-migration-guide-for-plugins-loaders-20a79b927202

I have no clue how the plugin currently works.. I guess I could start with upgrading skip-amd-webpack-plugin to 1.0.0 and the webpack peer/dev dependency to 4.x.x, run `npm test` and see what breaks? Seems dangerous to go alone...

PS: As far as I can tell, this is the only blocker for upgrading to webpack 4, which promises much improve performance.

**Comment by jzaefferer** [comment]
Looks like the first hurdle is to migrate from CommonChunksPlugin to optimization.splitChunks: https://github.com/rxaviers/globalize-webpack-plugin/pull/87

PS: Maybe https://gist.github.com/gricard/e8057f7de1029f9036a990af95c62ba8 and https://webpack.js.org/plugins/split-chunks-plugin/ can help, too.

**Comment by rxaviers** [comment]
Jörn, I couldn't dig into it, but your direction seems correct to me.

FWIW, I often find very helpful to look into webpack source code in addition to reading their documentation.

My tip is to compare webpack source code v3...v4 to find out what changes are required. For example, let's take `compiler.plugin("this-compilation", (compilation) => {` ([code](https://github.com/rxaviers/globalize-webpack-plugin/blob/master/ProductionModePlugin.js#L123)), changed from [this](https://github.com/webpack/webpack/blob/v3.12.0/lib/EnvironmentPlugin.js#L39) to [that](https://github.com/webpack/webpack/blob/f1092ad/lib/EnvironmentPlugin.js#L43).

**Comment by nfdevil** [comment]
+1 webpack 4 is the standaard now
