### ISSUE TITLE
Dynamically assign developmentLocale

### ISSUE THREAD

**Issue by PawelK2012** [rxaviers/globalize-webpack-plugin#84]
I wonder if there is a way to dynamically  assign value to `developmentLocale`? For example I would like to access `window.navigator.language` and assign it to `developmentLocale` inside `webpack-config.js`.

**Comment by rxaviers** [comment]
Can you explain your use case please? I don't get why would you want it...

**Comment by PawelK2012** [comment]
Nevermind. It was so long ago I don't even remember.

**Comment by rxaviers** [comment]
Thanks for replying and sorry for the very long time to get to your issue.
